twig:
    default_path: '%kernel.project_dir%/templates'

        # form_themes: ['bootstrap_5_horizontal_layout.html.twig']
    globals:
        baseUrl: 'http://127.0.0.1:8000'

when@test:
    twig:
        strict_variables: true
